### ISSUE TITLE
[DOC] Создать wiki страницу с описанием реализуемой структуры данных

### ISSUE THREAD

**Issue by JorgenPo** [JorgenPo/JavaPractice2016#2]
Необходимо описать (доходчиво и полно) реализуемую структуру данных (Красно-Черное дерево). В описании должны присутствовать картинки, схемы, пояснения ко всем операциям, планируемым для реализации.

**Comment by comaralex** [comment]
Wiki-Страница: Описание структуры данных Красно Черное дерево.

**Comment by JorgenPo** [comment]
Готово
