### ISSUE TITLE
[Design] Создать GUI прототип приложения

### ISSUE THREAD

**Issue by JorgenPo** [JorgenPo/JavaPractice2016#5]
Согласно описанию на wiki необходимо создать прототип (или макет) графического интерфейса пользователя приложения. Это необходимо сделать либо непосредственно в коде, либо с помощью графического редактора. Я думаю, что графический редактор предпочтительнее, так как с помощью него можно быстрее делать и изменять макет.

**Comment by comaralex** [comment]
Commit [GUI] RBTree_GUI - 92ebd13f40fbde59cd05e783d162f40c28ed80c3
